### PR TITLE
Add phrase searching

### PR DESCRIPTION
**Pull request by Matasin**

### CODE REVIEW

**Review by LukaszBielsko — CHANGES_REQUESTED** [review]
### It does not look very nice. What do you think?  Unleash your imagination :)
image

**Comment by Matasin** [comment]
> ### It does not look very nice. What do you think? Unleash your imagination :)
> image

You mean "nothing found"?

May i paste there some funny svg?

**Comment by LukaszBielsko** [comment]
Please fix `nothing found` jumping image :)

**Comment by Matasin** [comment]
> Please fix `nothing found` jumping image :)



> Please fix `nothing found` jumping image :)

Sure :)

**Pull request merged**
