### PR TITLE
Tooltip: seo links inside

### PR DESCRIPTION
**Pull request by Matasin**

### CODE REVIEW

**Review by LukaszBielsko — CHANGES_REQUESTED** [review]
### 1. Disable tooltip when editing a post.
image

### 2. Categories are broken when adding a new post. Also disable tooltip.
image

### 3. Some of the tooltip links work, some of them do not (they look like below example)
image

**Comment by Matasin** [comment]
> > ### 1. Disable tooltip when editing a post.
> > image
> > ### 2. Categories are broken when adding a new post. Also disable tooltip.
> > image
> > ### 3. Some of the tooltip links work, some of them do not (they look like below example)
> > image
> 
> Okey

Interesting thing, it must be because we changed object of categories

**Comment by Matasin** [comment]
> > ### 1. Disable tooltip when editing a post.
> > image
> > ### 2. Categories are broken when adding a new post. Also disable tooltip.
> > image
> > ### 3. Some of the tooltip links work, some of them do not (they look like below example)
> > image
> 
> Okey

i think they are not broken it can be side effect of using seo links in react

**Comment by Matasin** [comment]
Done but we might have an issue with POST on api, by new categories

**Comment by Matasin** [comment]
undefinds

**Comment by Matasin** [comment]
isHidden

**Pull request merged**
